sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pfanourgakis/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pfanourgakis/docker-react npm run test
