FROM node:alpine

WORKDIR "/app"

COPY package.json .
RUN npm install

# In our example , we could remove the follow command,
# but at some point we might need to clone or deprecate or not use the volumes,
# it is an essential command
COPY . .

CMD ["npm", "run", "start"]